import { useEffect, useState } from "react";
import { Link } from "@tanstack/react-router";
import { supabase } from "@/integrations/supabase/client";

/**
 * Blocking consent gate.
 *
 * The signup form gates its own submit on the terms checkbox, but Google
 * sign-in is a single button that also *creates* an account on first use —
 * so a first-time Google user who lands straight on an app page had never
 * accepted the terms. This checks the stored acceptance on the user record
 * and blocks the app until it exists, whichever door they came through.
 */
export function ConsentGate() {
  const [needed, setNeeded] = useState(false);
  const [agreed, setAgreed] = useState(false);
  const [marketing, setMarketing] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    supabase.auth.getUser().then(({ data }) => {
      if (!active || !data.user) return;
      const meta = data.user.user_metadata ?? {};
      if (meta.terms_accepted_at) return;

      // Consent captured on the auth page just before the OAuth redirect.
      let pending: { terms_accepted_at?: string; marketing_opt_in?: boolean } | null = null;
      try {
        const raw = window.localStorage.getItem("aether_signup_consent");
        if (raw) pending = JSON.parse(raw);
      } catch {
        /* storage unavailable */
      }

      if (pending?.terms_accepted_at) {
        supabase.auth
          .updateUser({
            data: {
              terms_accepted_at: pending.terms_accepted_at,
              marketing_opt_in: !!pending.marketing_opt_in,
            },
          })
          .then(() => {
            try {
              window.localStorage.removeItem("aether_signup_consent");
            } catch {
              /* ignore */
            }
          });
        return;
      }

      setNeeded(true);
    });
    return () => {
      active = false;
    };
  }, []);

  if (!needed) return null;

  async function accept() {
    if (!agreed) return;
    setBusy(true);
    setError(null);
    const { error } = await supabase.auth.updateUser({
      data: {
        terms_accepted_at: new Date().toISOString(),
        marketing_opt_in: marketing,
      },
    });
    if (error) {
      setError(error.message);
      setBusy(false);
      return;
    }
    setNeeded(false);
  }

  async function declineAndSignOut() {
    await supabase.auth.signOut();
    window.location.href = "/auth";
  }

  return (
    <div className="fixed inset-0 z-50 bg-background/95 backdrop-blur-sm flex items-center justify-center px-5 py-10 overflow-auto">
      <div className="w-full max-w-md border border-border bg-background p-6 sm:p-8">
        <p className="text-[10px] uppercase tracking-[0.3em] text-accent mb-5">One last thing</p>
        <h2 className="font-serif text-2xl sm:text-3xl font-light italic mb-6">
          Before you enter.
        </h2>

        <div className="space-y-4 mb-8">
          <label className="flex items-start gap-3 text-xs sm:text-sm font-light leading-relaxed text-stone-400 cursor-pointer">
            <input
              type="checkbox"
              checked={agreed}
              onChange={(e) => setAgreed(e.target.checked)}
              className="mt-1 size-4 shrink-0 accent-[#C2A378]"
            />
            <span>
              I agree to the{" "}
              <Link to="/terms" className="text-accent underline underline-offset-4">
                Terms of Service
              </Link>{" "}
              and{" "}
              <Link to="/privacy" className="text-accent underline underline-offset-4">
                Privacy Policy
              </Link>
              , and I acknowledge that readings are generated by AI for entertainment and reflective
              purposes only.
            </span>
          </label>
          <label className="flex items-start gap-3 text-xs sm:text-sm font-light leading-relaxed text-stone-400 cursor-pointer">
            <input
              type="checkbox"
              checked={marketing}
              onChange={(e) => setMarketing(e.target.checked)}
              className="mt-1 size-4 shrink-0 accent-[#C2A378]"
            />
            <span>Optional — send me promotional offers and astrology updates by email.</span>
          </label>
        </div>

        {error && (
          <p className="text-sm text-destructive-foreground bg-destructive/20 border border-destructive/40 px-4 py-2 mb-4">
            {error}
          </p>
        )}

        <button
          type="button"
          onClick={accept}
          disabled={!agreed || busy}
          className="w-full bg-accent text-primary-foreground py-3 font-serif italic text-lg hover:bg-stone-100 transition-colors disabled:opacity-40 disabled:hover:bg-accent"
        >
          {busy ? "…" : "Continue"}
        </button>
        <button
          type="button"
          onClick={declineAndSignOut}
          className="w-full mt-3 text-[10px] uppercase tracking-[0.2em] text-muted-foreground hover:text-accent transition-colors"
        >
          Sign out instead
        </button>
      </div>
    </div>
  );
}
